### ISSUE TITLE
Aws s3 don't work

### ISSUE THREAD

**Issue by marvin-zhao** [june07/nodebb-plugin-cloudstorage#2]
```
2019-08-28T08:05:49.848Z [4567/1207] - error: uncaughtException: Cannot read property 'Key' of undefined
TypeError: Cannot read property 'Key' of undefined
    at ManagedUpload.callback (/usr/src/app/node_modules/nodebb-plugin-cloudstorage/lib/controllers.js:218:93)
    at Response.finishSinglePart (/usr/src/app/node_modules/aws-sdk/lib/s3/managed_upload.js:674:28)
    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:38:9) {"error":{"message":"Cannot read property 'Key' of undefined","code":"TypeError","time":"2019-08-28T08:05:49.836Z"},"stack":"TypeError: Cannot read property 'Key' of undefined\n    at ManagedUpload.callback (/usr/src/app/node_modules/nodebb-plugin-cloudstorage/lib/controllers.js:218:93)\n    at Response.finishSinglePart (/usr/src/app/node_modules/aws-sdk/lib/s3/managed_upload.js:674:28)\n    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:364:18)\n    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:38:9)","exception":true,"date":"Wed Aug 28 2019 08:05:49 GMT+0000 (UTC)","process":{"pid":1207,"uid":0,"gid":0,"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","version":"v8.16.0","argv":["/usr/local/bin/node","/usr/src/app/app.js"],"memoryUsage":{"rss":344420352,"heapTotal":147755008,"heapUsed":118478416,"external":19247672}},"os":{"loadavg":[0.74560546875,0.3125,0.15673828125],"uptime":340588},"trace":[{"column":93,"file":"/usr/src/app/node_modules/nodebb-plugin-cloudstorage/lib/controllers.js","function":"ManagedUpload.callback","line":218,"method":"callback","native":false},{"column":28,"file":"/usr/src/app/node_modules/aws-sdk/lib/s3/managed_upload.js","function":"Response.finishSinglePart","line":674,"method":"finishSinglePart","native":false},{"column":18,"file":"/usr/src/app/node_modules/aws-sdk/lib/request.js","function":null,"line":364,"method":null,"native":false},{"column":20,"file":"/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js","function":"Request.callListeners","line":106,"method":"callListeners","native":false},{"column":10,"file":"/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js","function":"Request.emit","line":78,"method":"emit","native":false},{"column":14,"file":"/usr/src/app/node_modules/aws-sdk/lib/request.js","function":"Request.emit","line":683,"method":"emit","native":false},{"column":10,"file":"/usr/src/app/node_modules/aws-sdk/lib/request.js","function":"Request.transition","line":22,"method":"transition","native":false},{"column":12,"file":"/usr/src/app/node_modules/aws-sdk/lib/state_machine.js","function":"AcceptorStateMachine.runTo","line":14,"method":"runTo","native":false},{"column":10,"file":"/usr/src/app/node_modules/aws-sdk/lib/state_machine.js","function":null,"line":26,"method":null,"native":false},{"column":9,"file":"/usr/src/app/node_modules/aws-sdk/lib/request.js","function":null,"line":38,"method":null,"native":false}]}
2019-08-28T08:05:49.850Z [4567/1207] - error: Cannot read property 'Key' of undefined {"code":"TypeError","time":"2019-08-28T08:05:49.836Z"}
```

**Comment by june07** [comment]
Can you share what file you are trying to upload...

**Comment by marvin-zhao** [comment]
I uploaded a picture. I modified the code to print err. I found that the reason was aws-sdk prompted AccessDenied. But I tried to use aws-sdk and my accesskey/sercetkey to upload the picture successfully.

**Comment by marvin-zhao** [comment]
https://github.com/june07/nodebb-plugin-cloudstorage/blob/master/lib/controllers.js#L214
`if (err) reject(err);` can't catch error. The err causes nodebb to restart.

I'm not a nodejs developer and don't know much about the language.

**Comment by marvin-zhao** [comment]
I found the reason that my bucket wasn't public. 

But can't catch error  is still a problem

**Comment by june07** [comment]
Pushed a fix.  Should have been returning after that reject call.  Thanks for the help.

https://github.com/june07/nodebb-plugin-cloudstorage/commit/05f437482500a9605d3c51e8c4632b9e011a99a0#diff-6b49b62ca6c8a7110bdda9c1189098aeR214-R215
